### ISSUE TITLE
Problem with incoming call.

### ISSUE THREAD

**Issue by tuanngodoan** [twilio/voice-quickstart-ios#117]
### Description

Two months ago, when i export .pem file, i used Apple Push Notification. It seems normal operation(can register, call, etc...). After, I changed to VoIP Service for export .pem file. Then my app still can register Twilio, call...
Now, I use again Apple Push Notification. I can't have success call and have Error code-52134. Then, I change back with VoIP, my application can work great again with call.

Question:
- Why i can't use Apple Push Notification anymore?
- What should i do next for can  receive incoming call? Should use VoIP right?

Thank for great "Programmable Voice" . Hope you can support me.

#### Voice iOS SDK

- 2.0.0-beta19 via Manually Install.

#### Xcode

- Version 9.2

#### iOS Version

- Version > 10.x.x

**Comment by bchen-twilio** [comment]
Hi @tuanngodoan 

In order to make the call push notification work using the Twilio Voice SDK, especially the iOS SDK, you will need the VoIP Service certificate from Apple. Using the APNS certificate will cause the Twilio service problem to send the notification to the incorrect Apple notification service endpoint. 

One important thing about the VoIP Service certificate is that you will need a freshly generated CSR (certificate signing request) file when requesting for the VoIP Service certificate. One common error we've been seeing is that developers use their existing APNS certificate with the Twilio Voice SDK or use the CSR file that was previously used for requesting the APNS certificate when generating the VoIP Service certificate.

Thanks
-bobie

**Comment by ramohanreddy** [comment]
Hi @bchen-twilio 
I created new VoIP certificate for incoming call but i am not able to get any call .
Can u suggest me any solution for this.

**Comment by bchen-twilio** [comment]
Hi @tuanngodoan 

Just to touch base with you and see if the original problem has been resolved?

Hi @ramohanreddy 

Please provide Call SID so we can diagnose if there is any issue.

Thanks.

**Comment by piyushtank** [comment]
@tuanngodoan and @ramohanreddy Hoping the issue has been resolved. I am closing the old ticket. Feel free to reopen if you run into the same issue or have any questions.
