### ISSUE TITLE
iOS 13 Apps built on Xcode 11 may terminate your app when TVOCancelledCallInvite is received

### ISSUE THREAD

**Issue by piyushtank** [twilio/voice-quickstart-ios#251]
Starting with iOS 13, Apple mandates the use of CallKit when PushKit is used. An iOS app must report incoming calls with CallKit in the `didReceiveIncomingPush` callback or the app will be [terminated](https://developer.apple.com/documentation/pushkit/pkpushregistrydelegate/2875784-pushregistry). And, if an app repeatedly does this, or if it repeatedly fails not to report an incoming call, the system may stop launching the app for VoIP pushes altogether. See WWDC19 Session [here](https://developer.apple.com/videos/play/wwdc2019/707/). 

In our experiments, we observed iOS 13 expects an app to report an incoming VoIP push to CallKit when the app is in suspended state. If an app is in the suspended state and if the app fails to report an incoming call to CallKit, iOS 13 terminates the app with following message - 

```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'PushKit apps that use VoIP push must link either CallKit or IncomingCallNotifications frameworks.’
``` 

With TwilioVoice SDK, an app is expected to receive VoIP pushes for : `TVOCallInvite` and `TVOCancelledCallInvite`. 

We performed some tests and here is a summary of our findings:

Scenario: Alice calls Bob, Bob receives the call via PushKit

|  App state-> | Active  | Background  | Suspended  | Killed  |
|---|---|---|---|---|
| Bob answers the call  | ✅  | ✅  |✅   |  ✅ |
| Bob ignores the call  | ✅  | ✅  | ✅  | ✅  |
| Alice calls Bob and hangs up before Bob answers  | ✅  | ✅  |  ✅ | ✅  |
| Bob rejects Alice's call |  ✅ | ❌  | ❌  | ❌  |

✅= Works as expected
❌= iOS 13 throws an exception

Most cases work as expected since the app is not in the suspended state because the CallKit UI is present, however when an incoming call is rejected, if the `TVOCancelledCallInvite` push notification arrives after the app has gone into the suspended state, iOS 13 will throw an exception.

### Workaround

When a  `TVOCancelledCallInvite` push notification is received when an associated incoming call invite is not found due to it was rejected or if the call invite was lost, as a workaround, report a new incoming call to CallKit, and then end it on the next tick.

```swift
func cancelledCallInviteReceived(_ cancelledCallInvite: TVOCancelledCallInvite) {
    NSLog("cancelledCallInviteCanceled:")
    
    self.incomingPushHandled()
    
    if (self.callInvite == nil ||
        self.callInvite!.callSid != cancelledCallInvite.callSid) {
        NSLog("No matching pending CallInvite. Ignoring the Cancelled CallInvite")

        if #available(iOS 13.0, *) {
            // Ignoring the cancel when CallKit has a Call in progreass.
            if (self.call?.state != TVOCallState.disconnected) {
                return;
            }

            // iOS 13 workaround
            let uuid = UUID()
            reportIncomingCall(from: "Voice Bot", uuid: uuid)

            DispatchQueue.main.async {
                self.performEndCallAction(uuid: self.callInvite!.uuid)
            }
        }
        return
    }
    
    performEndCallAction(uuid: self.callInvite!.uuid)

    self.callInvite = nil
    self.incomingPushHandled()
}
```

### Note

Please note that we are working on this problem to avoid the workaround in iOS apps using the Voice SDK. We will use this ticket to track and post updates on this issue.

**Comment by ecstasy2** [comment]
Does this affect only apps built using SDK13 or will it affect apps that keep using SDK12 for now?

Thanks.

**Comment by piyushtank** [comment]
@ecstasy2 This affects only the iOS 13 only. iOS 12.x and prior versions are OK.

**Comment by ecstasy2** [comment]
Sorry if I am not getting this. I understand that it affects iOS 13 only. But say I have an app already in the app store, built with iOS 12 SDK. Am I forced to make this change if I don't intend to upgrade the app?

**Comment by piyushtank** [comment]
@ecstasy2 It impacts only the apps built using Xcode 11 on iOS 13. Which means your existing app store app will work as expected on iOS 12 and iOS 13 devices.

**Comment by wcrtr** [comment]
Is the iOS 13 issue also resulting in failure to register via TwilioVoice.register(etc etc)? I just started adapting my app with Xcode 11 and am seeing errors from this call and have not changed anything (verified my app sids, etc etc). Thanks!

**Comment by bchen-twilio** [comment]
Hi @wcrtr 

I believe you are hitting the same device token decode issue that is introduced in the new iOS 13 SDK. Please check out the [fix here](https://github.com/twilio/voice-quickstart-swift/pull/257/files) and try the registration again.

Thanks,
-bobie

**Comment by wcrtr** [comment]
@bchen-twilio my bad - missed that! Thanks!

**Comment by piyushtank** [comment]
Hello, 

We have released iOS Voice SDK 5.0.0 which allows developers to build iOS applications on iOS 13+ using Xcode 11+. 

[Here](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog) are the change logs and [here](https://github.com/twilio/twilio-voice-ios/blob/Releases/iOS-13-Migration-Guide.md) is the iOS 13 migration guide.

Thank you,
Piyush

**Comment by mmartikainen** [comment]
Congratulations! 🎉 

Best,
Magnus

**Comment by ceaglest** [comment]
Great news, nice job Voice team! 💯

**Comment by mroffmix** [comment]
I had the same 
pushRegistry:didReceiveIncomingPushWithPayload:forType:completion:
INFO:Twilio:[Core]:Creating peer connection signaling thread ...
INFO:Twilio:[Core]:Creating peer connection worker thread ...
INFO:Twilio:[Core]:Creating peer connection networking thread ...
TRACE:Twilio:[Core]:Creating built-in AudioDecoderFactory ...
TRACE:Twilio:[Core]:Creating built-in AudioEncoderFactory ...
INFO:Twilio:[Core]:Creating media engine ...
INFO:Twilio:[Core]:Done creating media engine.
INFO:Twilio:[Core]:Creating peer connection factory ...
INFO:Twilio:[Core]:Done creating peer connection factory.
INFO:Twilio:[Core]:Creating dedicated notifier queue ...
DEBUG:Twilio:[Core]:Initializing SIP stack ...
DEBUG:Twilio:[Core]:Adding IPv4/IPv6 TLS transports ...
INFO:Twilio:[Signaling]:RESIP::TRANSPORT: Connection::Connection: new connection created to who: [ V4 0.0.0.0:0 UNKNOWN_TRANSPORT target domain=unspecified mFlowKey=0 ]
INFO:Twilio:[Signaling]:RESIP::TRANSPORT: Creating TLS transport for domain  interface= port=0
INFO:Twilio:[Signaling]:RESIP::TRANSPORT: Connection::Connection: new connection created to who: [ V4 0.0.0.0:0 UNKNOWN_TRANSPORT target domain=unspecified mFlowKey=0 ]
INFO:Twilio:[Signaling]:RESIP::TRANSPORT: Creating TLS transport for domain  interface= port=0
DEBUG:Twilio:[Core]:Initializing DUM ...
DEBUG:Twilio:[Core]:Starting SIP stack thread ...
DEBUG:Twilio:[Core]:Starting DUM thread ...
DEBUG:Twilio:[Core]:AppleReachability::AppleReachability()
DEBUG:Twilio:[Core]:Creating zeroAddrReachability
DEBUG:Twilio:[Core]:listen
DEBUG:Twilio:[Core]:ListenerImpl
callInviteReceived:
DEBUG:Twilio:[Core]:New SipCall ..., this=0x10a831000
INFO:Twilio:[Core]:Looking up: chunderm.gll.twilio.com
Apps receving VoIP pushes must post an incoming call (via CallKit or IncomingCallNotifications) in the same run loop as   pushRegistry:didReceiveIncomingPushWithPayload:forType:[withCompletionHandler:] without delay.
*** Assertion failure in -[PKPushRegistry _terminateAppIfThereAreUnhandledVoIPPushes], /BuildRoot/Library/Caches/com.apple.xbs/Sources/PushKit/PushKit-36/PKPushRegistry.m:343
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.'
*** First throw call stack:
(0x181aca98c 0x1817f30a4 0x1819ccd1c 0x181e028f4 0x1955cba5c 0x109bfac04 0x109c09888 0x1955ca9cc 0x109bf9828 0x109bfac04 0x109c08c64 0x181a483c4 0x181a433b8 0x181a428bc 0x18b8ae328 0x185ad86d4 0x104ec2970 0x1818cd460)
libc++abi.dylib: terminating with uncaught exception of type NSException
Message from debugger: Terminated due to signal 9

**Comment by bchen-twilio** [comment]
Hi @mroffmix 

It seems that the application either failed to report the VoIP push as CallKit incoming call at all or  before the execution went out of the scope of the did-receive-incoming-push PushKit callback method.

Please follow the [iOS 13 migration guide](https://github.com/twilio/twilio-voice-ios/blob/Releases/iOS-13-Migration-Guide.md) and make sure that:
1. The application calls the `TwilioVoice.register()` method to update the registration for only the call notification. Cancel notification is deprecated and SDK will handle the cancellation internally.
2. Always report VoIP push notifications as CallKit new incoming calls upon receiving PushKit notifications.

Thanks,
-bobie

**Comment by vaibhavtech1302** [comment]
Can we handle same thing with FCM notification on iOS please send me sample code for FCM if it's possible and I am unable to create key from voip certificate for iOS can anyone send me video guide to implement this process.

Thanks!
