### ISSUE TITLE
What support does we receive for 2.x after 1/1/2020?

### ISSUE THREAD

**Issue by monoqlo** [twilio/voice-quickstart-ios#290]
> Support for 2.x will cease 1/1/2020. Until then, SDK 2.x will only receive fixes for critical or security related issues.

https://github.com/twilio/voice-quickstart-swift/blame/master/README.md#L3

Hi, we're migrating to 5.x, but it will finish after the deadline.
Could you tell me about the detail?

I think "critical or security related issues" don't include a small bug fix, for example a call disconnects unexpectedly under certain conditions.

What support does we receive for 2.x after 1/1/2020?
For example, can we receive your support if a problem occurs caused by Apple, that is 
destructive Xcode/iOS SDK update like iOS 13 ?

Best regards.

**Comment by bchen-twilio** [comment]
Hi @monoqlo 

Thanks for contacting us. With the new PushKit policy in iOS 13, it's highly recommended that applications upgrade to the latest Voice iOS SDK to ensure the best user experience. We have put together a full migration guide for apps to update their implementations but we are also more than happy to assist the upgrade.

Please provide us more information about the disconnect problem (SDK version, what actions are performed, SDK logs, Twilio Call SIDs, etc.) if the issue is still happening in your environment.

The Voice iOS SDK 2.1 already has the updates that are required to ensure the application/SDK can function properly on iOS 13.

Thanks,
-bobie
