### ISSUE TITLE
52134 Invalid APNs device token [ios 11.0.3]

### ISSUE THREAD

**Issue by w33z** [twilio/voice-quickstart-ios#304]
### Description

In Twilio dashboard I see error(52134 Invalid APNs device token) and my call not reach out on iphone 6.
I call from my app to 3 devices. Two of them is reaching call, but in console debugger two iPhone 6 gets 52134. However iphone 6 on 12.3.1 works. 

#### Expected Behavior

Make a voice call.

#### Actual Behavior

Call start on two devices but not reach on iPhone 6 [11.0.3]

#### Logs

```
12.3.1

bindingType | "apn"
-- | --
primaryCorrelationId | "CA96617cb664a94e82d9e819a7bbc99b08"
bindingSid | "BSa6671e861fba5bf87cabbc475dcf953a"
providerMessageId | "c44fb763-163b-130f-632b-de0c5ae521f3"
requestId | "RQaf9d7adbe506b16eb26d0a380f95d59e"
notificationSid | "NT26a16d842066f995de39517553c1d8af"
module | "APNSBA"
description | "The specified device token is either malformed or not valid for the given environment."
isPassthrough | "true"
deliverySid | "DAb35fd1ace12d75c251e9c648ceda946e"
fromReference | "CR0171ff39dfe5568b12ff5e65b920b3e8"

11.0.3
bindingType | "apn"
-- | --
primaryCorrelationId | "CA7b15d1ca9ed0b1c92d3c923dce7eee27"
bindingSid | "BSd973c11a922876134677337196fd6417"
providerMessageId | "05f74f61-c18d-f876-1507-01f70015bf79"
requestId | "RQf7a317301da60ea045c9be2cb3b35300"
notificationSid | "NT69a15261987e6c9008a349c7d459a430"
module | "APNSBA"
description | "The specified device token is either malformed or not valid for the given environment."
isPassthrough | "true"
deliverySid | "DAdb8c61c1a09b3f13cb552972d717f164"
fromReference | "CR0171ff39dfe5568b12ff5e65b920b3e8"



```

#### Voice iOS SDK

5.0/5.1.1

#### Xcode

11.3.1

#### iOS Device

All device successfully registered for VoIP push notifications. 

Works:
iPhone Xs [13.3], iPhone 6 [12.3.1]

Not works:
iPhone 6 [11.0.3] 

With SANDBOX unticked, the result is 52134 Invalid APNs device token
Entitlements is production.
I tested with the phones using TestFlight versions.

**Comment by bchen-twilio** [comment]
Hi @w33z 

Thanks for reaching out to us.

This is a commonly seen issue when the device is used previously with development entitlement and later in a production environment. We have observed that in this case the device token returned in the PushKit delegate method will be for the previous environment (development entitlement device token) when launching the TestFlight app for the first time. Although registration still works since both the device token format and the Push Credential SID are valid, but error will happen when Twilio tries to send the notification delivery request to APNS.

Ideally this will only happen to the dev devices and to resolve this you simply need to relaunch the TestFlight app then it should be able to receive incoming call notifications.

Hope this helps.

Cheers,
-bobie

**Comment by w33z** [comment]
Thanks for your reply.

I've successfully connected with all 3 devices. But i'm still getting in console 52134. Should i worry about it?

**Comment by bchen-twilio** [comment]
Hi @w33z 

Thanks for the update and glad to see that you are able to connect calls for all your devices.
The error in the console could be caused by some cached notification binding associated with the same identity that still exists in the database, but was created with the PushKit device token from the development entitlement. You should not have to worry about this problem unless the error is occurring in the production environment.

Cheers,
-bobie
