### ISSUE TITLE
Hi I want to I identify call is received

### ISSUE THREAD

**Issue by TechnoBrigadeInfotech** [twilio/voice-quickstart-ios#312]
### Description
Hi I want to I identify call receive moment   

### Steps to Reproduce
If Client "A" call to a client "B"
how can Client "A" identify Client "B" has received a call

Versions
All relevant version information for the issue.

Voice iOS SDK
Using TwilioVoice (5.1.1)

Xcode
Xcode 11.2.1

iOS Version
All versions above 10

iOS Device
On All Devices

**Comment by bchen-twilio** [comment]
Hi @TechnoBrigadeInfotech 

Sorry for my delay of responding back to you.

To track if the call has been answered by the called party, you can enable [the answerOnBridge flag](https://www.twilio.com/docs/voice/twiml/dial#answeronbridge) in your <Dial> verb, that way the caller client will only receive the `callDidConnect:` callback when the call is accepted.

To track if the call has been received by the callee, currently there is no callback to notify the caller since the Voice SDK is relying on Apple's APN service to delivery the push notifications to the called client and they do not provide any status callback to inform our service whether a notification has been received by the device.
One way you can implement a reporting mechanism on the client application to signal your service that the notification (incoming call) has been received by the callee client and then the service can notify the caller client with the update.

Hope this answers your question.

Cheers,
-bobie

**Comment by TechnoBrigadeInfotech** [comment]
ok Got it

Sir How can I pass custom parameters in a voice call, I read the documentation but I can't understand
So please give a solution.

**Comment by bchen-twilio** [comment]
Hi @TechnoBrigadeInfotech 

Please file a separate issue for the custom parameters, and please give us the details which part of the documentation is confusing or what problems you are experiencing.

I'll close this ticket since the question has been answered.

Cheers,
-bobie
