### ISSUE TITLE
SDK size is large then documented

### ISSUE THREAD

**Issue by ostap0207** [twilio/voice-quickstart-ios#321]
### Description

SDK size is different from reported in https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#size-impact-for-520.

### Steps to Reproduce

1. Add Twilio to Podfile
2. Archive the app
3. Export the archive (rebuild bitcode checked)
4. The report shows an uncompressed app size increase for specific architecture of ~12 MB. The universal app size increase is ~ 17MB.

Is there anything I am missing to make the report show expected 5-7MB?

**Comment by ostap0207** [comment]
I've started with the simple almost empty app and here is the report:
Before adding Twilio: 
[App Thinning Size Report.txt](https://github.com/twilio/voice-quickstart-ios/files/4313082/App.Thinning.Size.Report.txt)
The size ranges from 2,1 MB to 8,5 MB uncompressed. Universal is: 16 MB uncompressed

After adding Twilio:
[App Thinning Size Report.txt](https://github.com/twilio/voice-quickstart-ios/files/4313080/App.Thinning.Size.Report.txt)
The size ranges from 14,1 MB to 20,5 MB uncompressed. Universal is: 33,7 MB uncompressed.

Expected: size ranges from ~8MB to ~ 14MB uncompressed. Universal: 28 MB.

**Comment by piyushtank** [comment]
@ostap0207 We are looking into this and will have an update for you soon.

**Comment by bchen-twilio** [comment]
Hi @ostap0207 

Sorry for my delay of responding back to you.
Our size impact report is generated based on an empty app (Objective-C) with minimal `TwilioVoice.framework` integration:
- `TwilioVoice.framework` imported in the embedded framework list
- The framework is imported by calling `@import TwilioVoice;`
- Use the `TwilioVoice.sdkVersion()` method to print out the version when the app is launched
- Archive & Export:
```
xcodebuild \
  -workspace APP_WORKSPACE \
  -scheme APP_SCHEME \
  -configuration Release \
  -sdk iphoneos \
  -parallelizeTargets \
  ONLY_ACTIVE_ARCH=NO \
  BITCODE_GENERATION_MODE=bitcode \
  archive

xcodebuild \
  -exportArchive \
  -archivePath "${ARCHIVE_PATH}" \
  -exportPath "${IPA_DIR}" \
  -exportOptionsPlist EXPORT_OPTIONS_PLIST
```

Also in the basic app, we use a script that comes with the framework at the end of Build Phases to remove simulator architectures from the framework that is embedded with the app.

This is the [thinning report](https://github.com/twilio/voice-quickstart-ios/files/4341585/App.Thinning.Size.Report.txt) and the [export options plist](https://github.com/twilio/voice-quickstart-ios/files/4341587/enterprise-plist.txt).

The final numbers are determined by unzipping app .ipa and extracting the size of the `TwilioVoice.framework` in architectures.

I am curious if it's possible for you to share the basic app since you mentioned that you are using Cocoapods as the dependency tool. I've tried using Cocoapods and did see similar amount (~6MB) of size increase from the uncompressed app, compared to the manual way of importing TwilioVoice. You can file a [Twilio Support](https://support.twilio.com/hc/en-us) ticket and tag the Programmable Voice SDK engineering team if you don't feel safe sharing your app project here.

Best,
-bobie

**Comment by paynerc** [comment]
@ostap0207 

We've been investigating this further and I think we understand where the size discrepancy is coming from. With that being said we don't need you to send over your project.

We will keep you posted.

Ryan

**Comment by ostap0207** [comment]
@paynerc thank you!

**Comment by paynerc** [comment]
@ostap0207 

I am happy you uncovered this issue. As it turns out, this appears when Twilio Voice (and for that matter, Video) is consumed via either Carthage or Cocoapods. What is happening is that a long time ago, we began shipping the `BCSymbolMaps` that were created for a framework *inside* the framework so that a developer had access to them while building with our SDKs. We provide a script inside the framework, `remove_archs`, that strips the simulator architecture out of a device build, and vice versa. Back when we started we were supporting manual integration of the framework and we have a step in the [docs](https://www.twilio.com/docs/voice/voip-sdk/ios#manual-install) that says to add this script as a run phase. This script does something else, beside stripping the unneeded architectures: It also moves the `BCSymbolMap` files out of the framework and into the build folder where they would normally go when compiling an application.

When Cocoapods and Carthage support was added, each of these tools has their own way of stripping unneeded architectures out of embedded frameworks, so we suggest customers use the approaches specific to each tool.

These tools, however, don't do anything with the `BCSymbolMaps` files.

I am creating tickets for both Voice and Video iOS SDKs to investigate whether it still makes sense to distribute the `BCSymbolMap` files and what the best approach is. They aren't beneficial *inside* an application and only increases the size.

With all that said, in the meantime, you can manually add a Run Script Build phase as noted in the [iOS installation instructions](https://www.twilio.com/docs/voice/voip-sdk/ios#manual-install) and it will strip these out for you.

Again, thank you for finding this. Let me know if you have any further questions.

Ryan

**Comment by ostap0207** [comment]
@paynerc Thanks a lot for looking into this and finding the problem! We will try to use the instructions that you've provided for now.

**Comment by ostap0207** [comment]
Hi, any progress on this?
I've tried the provided instructions (https://www.twilio.com/docs/voice/voip-sdk/ios#manual-install), but was not able to get it working for our case.

We don't have an app, but we also build a library distributed via Cocoapods and Carthage, and we don't want our clients to have to include this script in their builds.

**Comment by bchen-twilio** [comment]
Hi @ostap0207 

Thanks for reaching out.
Since we haven't got the chance to evaluate the efforts to take the bitcode symbol map files out of the framework, you can follow @paynerc 's suggestion and add a step in your pipeline to remove the `BCSymbolMaps` under TwilioVoice.framework.

Sorry for the inconvenience.

**Comment by ostap0207** [comment]
Adding the script under `TwilioVoice.framework` causes an error. 
> TwilioVoice.framework/remove_archs: No such file or directory

Also as I mentioned before
>  We don't have an app, but we also build a library distributed via Cocoapods and Carthage, and we don't want our clients to have to include this script in their builds.

**Comment by bchen-twilio** [comment]
Hi @ostap0207 

Sorry for the delay of getting back to you.
Just want to let you know that we have created tickets to tracking the progress of some improvements around packaging the debug symbols with the SDK and will keep you updated.
