### ISSUE TITLE
Empty Credentials, in twilio debugger while initiating a call from iOS

### ISSUE THREAD

**Issue by yatindma** [twilio/voice-quickstart-ios#342]
I am trying to initiate a call from iOS then it's connecting for 2-3 sec and getting disconnected after that and in Twilio debugger we are getting "Empty Credentials", do you have any idea regarding the same.

**Comment by bchen-twilio** [comment]
Hi @yatindma 

Thanks for writing in. It would be great if you can share more detail about the problem you ran into, such as the steps, Twilio Call SID and SDK log so that we can help you out.

From you description I would suggest having a look at the access token and check if you have all your account credentials in it.

**Comment by bchen-twilio** [comment]
Hi @yatindma 

Hope things are well.
Did you get a chance to gather more information, logs or Twilio Call SIDs, regarding the issue you are running into?

**Comment by bchen-twilio** [comment]
Closing ticket since there has been no updates. Please feel free to reach out to the SDK team.
