### ISSUE TITLE
Twilio using custom UI for incoming calls

### ISSUE THREAD

**Issue by Priyankaamt** [twilio/voice-quickstart-ios#343]
Can we use the twilio services without call kit and instead of call kit UI can we use our custom UI for incoming calls in ios ? 
One we got the notification from twilio of incoming calls. Is it possible to open the custom Incoming UI screen so that we can have a control of accept and rejecting the calls instead of showing the system call kit incoming call screen.

**Comment by bchen-twilio** [comment]
Hi @Priyankaamt 

The Voice iOS SDK uses Apple's VoIP notification to notify mobile clients of incoming call invites and with PushKit + CallKit policy of the latest iOS (13), reporting to CallKit is mandatory. Native call UI will pop up once the incoming call is reported to CallKit, but app users can tap on the app icon in the system call UI to go back to the application if the incoming is received when the device is not locked.

**Comment by Priyankaamt** [comment]
Thanks for the response. 
I have one more query

Our use case is to display some Tags and Call subject information in the incoming call screen. We would like to show this information to users before they pick up the call. Is there any hack/workaround possible.
![image_2020_05_06T04_39_50_447Z](https://user-images.githubusercontent.com/64835168/81142896-6fada380-8f8e-11ea-890d-2d64f359d1c5.png)

**Comment by bchen-twilio** [comment]
Hi @Priyankaamt 

The system call UI only gives as much flexibility as the name that is reported to CallKit.

**Comment by Priyankaamt** [comment]
Thanks for the response @bchen-twilio.

**Comment by bchen-twilio** [comment]
@Priyankaamt You are welcome! Please feel free to reach out to us any time.

**Comment by Priyankaamt** [comment]
Hi @bchen-twilio ,
Is there any documentation for conference call in iOS . 
I have checked the documentation for twilio there backend api documentation, video conference . 
What I have to create is audio conference in iOS swift .
Regards
Priyanka!

**Comment by bchen-twilio** [comment]
Hi @Priyankaamt 

You can either use the Twilio Client API to create a conference and invite a mobile client by creating a participant with the identity you registered on the phone: https://www.twilio.com/docs/voice/api/conference-participant-resource

The mobile client can definitely start a conference by using the <Conference> verb in the TwiML application when calling `TwilioVoice.connect()`: https://www.twilio.com/docs/voice/twiml/conference

**Comment by Priyankaamt** [comment]
Thanks @bchen-twilio 
I have one more doubt.
I have created backend api with conference verb and from outgoing call it is working fine. I am able to listen a music on hold but the other end they are not receiving any VoIP notification to join the Conference Room. can we record the conference ?

Is there any solution for this problem?

**Comment by bchen-twilio** [comment]
Hi @Priyankaamt 

How are inviting the participant? did you receive any error when trying to add participant to your conference?

Since I am not the expert of Conference, I would recommend opening a [Twilio Support](https://support.twilio.com/hc/en-us) ticket so that we can get experts from the area to better assist you.

**Comment by Priyankaamt** [comment]
Thanks!

**Comment by Priyankaamt** [comment]
Hi @bchen-twilio ,
I have one more doubt. 
Sometimes I am receiving the call easily but some times I am getting this error 52143- the push notification was rejected by apns.
I checked the twilio token it is not expired. Can u please tell why this happens.
We are not able to find out the solution why this is happening because in some iphone devices it is working but after some it is not working .
Regards!
Priyanka

**Comment by bchen-twilio** [comment]
Hi @Priyankaamt 

Sorry for my delay of responding back to you.

I checked the Call SID and found that all bindings registered for the callee identity are FCM bindings. Perhaps you have other Call SIDs that you are experiencing problem receiving call notification for iOS mobile clients?

**Comment by Priyankaamt** [comment]
Hi @bchen-twilio ,
This is the SID - CAba6411a6265e48720e72df9566ed1f07
Here also sometimes I got the call but sometime I am not getting . And also cross check the sandbox button is checked.

**Comment by bchen-twilio** [comment]
Thanks for the new Call SID @Priyankaamt.

From the record I saw 4 notification delivery requests and 2 of them (both Apple VoIP) failed.

Push notifications to the mobile client, PushKit device token ending with `f3fa9151`, were sent successfully until May 19th. The Push Credential SID (`CRb94d58de1877e1023c36fcdbbb466cec`, non-sandbox) and the device token format have not changed.

The other one (device token ending `26384bbd`) is a little trickier. There are 3 Push Credential SIDs associated with this device and only one (`CRdca53a658f2a2eeb65bdbf8232eb1362`, sandbox) was able to successfully send notifications.

Could this be because the devices are used to installed both debug and production version of the app? An odd behavior of iOS could have caused some issue. For example I have observed that every time I install and launch a production version app on a device where I previously use for development and debugging (which is pretty common), PushKit will give me the device token of the dev entitlement. I will have to kill the app and launch again then PushKit will give me the correct device token for the production entitlement.

Anyway, can you find these two devices and check if my observation is applicable and helpful for debugging the issue?

Thanks,
-bobie
