### ISSUE TITLE
Question: "Your VoIP Services Certificate will no longer be valid in 30 days"

### ISSUE THREAD

**Issue by gerchicov-bp** [twilio/voice-quickstart-ios#347]
https://www.twilio.com/docs/voice/voip-sdk/ios/get-started#8-create-a-push-credential-with-your-voip-service-certificate
>8. Create a Push Credential with your VoIP Service Certificate

This section is clear except of one thing - what to do if I already have VoIP certificate (which will expire in few days) and a workable app in App Store. How to deal with it? Should I rebuild the iOS app and resend it to App Store?

**Comment by bchen-twilio** [comment]
Hi @gerchicov-bp 

Overall you don't need to change your application or your anything in the production environment. All you have to do is go to Apple's developer portal and renew the VoIP Service certificate. Once you have done that, follow the same steps of the quickstart, only this time you need to update the existing Push Credential SID with the new certificate and key instead of creating a new one.

Hope this answers your question.

-bobie

**Comment by gerchicov-bp** [comment]
Thanks
