### ISSUE TITLE
I want to get remote Audio stream during call ?

### ISSUE THREAD

**Issue by milanTbi** [twilio/voice-quickstart-ios#349]
Description
I want to get remote Audio stream during call

Steps to Reproduce
please help me how can i get live remote audio stream during call

Voice iOS SDK
Using TwilioVoice (5.1.1)

Xcode
Xcode 11.2.1

iOS Version
All versions above 10

iOS Device
On All Devices

**Comment by bchen-twilio** [comment]
Hi @milanTbi 

Thanks for reaching out.

We haven't provided the exact sample app for this purpose yet but you can take a look at TVOAudioDevice and use the interface to have deeper control of the local and remote audio:
- [TVOAudioDevice](https://twilio.github.io/twilio-voice-ios/docs/latest/Protocols/TVOAudioDevice.html) (doc is empty due to non-objc methods but you can find TVOAudioDevice.h in the framework)
- [TVOAudioDeviceCapturer](https://twilio.github.io/twilio-voice-ios/docs/latest/Protocols/TVOAudioDeviceCapturer.html)
- [TVOAudioDeviceRenderer](https://twilio.github.io/twilio-voice-ios/docs/latest/Protocols/TVOAudioDeviceRenderer.html)

The [Audio Device Example project](https://github.com/twilio/voice-quickstart-ios/tree/master/AudioDeviceExample) is also a great reference you can start with.

Feel free to let us know if you need assistance implementing your custom audio device.

-bobie

**Comment by milanTbi** [comment]
Hello 

Thanks for response


I have followed your above documentation but I can't get any solution please tell me which method or function give me remote audio stream during a call

**Comment by piyushtank** [comment]
@milanTbi - By implementing a custom audio device you can receive audio samples from remote participant. We have audio device example which demonstrates how to get audio samples - https://github.com/twilio/voice-quickstart-ios/blob/master/AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m#L332

let me know if you have any questions.

**Comment by milanTbi** [comment]
> @milanTbi - By implementing a custom audio device you can receive audio samples from remote participant. We have audio device example which demonstrates how to get audio samples - https://github.com/twilio/voice-quickstart-ios/blob/master/AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m#L332
> 
> let me know if you have any questions.

**Comment by milanTbi** [comment]
@piyushtank " custom audio device" means what?

**Comment by piyushtank** [comment]
@milanTbi Are you trying to make a Voip to Voip, or voip to pstn call ? can you clarify your use case please.

**Comment by milanTbi** [comment]
Hello @piyushtank Thank you for your support

we are work on voip to pstn call and I want an audio stream of pstn on voip side So please tell me how can I do it?

**Comment by imkhubaibraza** [comment]
Hello @milanTb i, I'm on the same boat, did you find any solution ?

**Comment by bobiechen-twilio** [comment]
Hi @imkhubaibraza 

Have you tried the ExampleAVAudioEngineDevice sample @piyushtank mentioned in the [previous comment](https://github.com/twilio/voice-quickstart-ios/issues/349#issuecomment-649724260)? Happy to assist if you need help using the `TVOAudioDevice` interface.

-bobie
