### ISSUE TITLE
Is there a way to use the default iOS screen call instead of my own UI?

### ISSUE THREAD

**Issue by JohnLennon145** [twilio/voice-quickstart-ios#353]
Hello,

I followed the tutorial to implement a basic app with VoIP. When the user is getting called (the phone is ringing), there is obviously no way to replace the iOS system UI, which is cool for me. 
I'm talking about this one:

<img width="183" alt="Capture d’écran 2020-05-29 à 10 19 44" src="https://user-images.githubusercontent.com/65609099/83237980-063c4180-a196-11ea-95c9-013441126ce3.png">

However, when the user answers the call, the default iOS screen appears for like 2-3 tenths of a second and then suddenly disappears, and I need to show my own UI instead. 
Oddly, when the user leaves the app and enters it again, this screen pops up again and this time doesn't disappear until anyone leaves the call. 
This is the screen I'm talking about : 

![IMG_7881](https://user-images.githubusercontent.com/65609099/83238389-a85c2980-a196-11ea-8087-3bd9e3f8f60d.jpg)

My question is simply, is there a way to always use this UI? Thank you for your help.

**Comment by bchen-twilio** [comment]
Hi @JohnLennon145 

I guess this is the way Apple/CallKit designed the behavior for the incoming calls.
Just curious - what did you do by 
> when the user leaves the app and enters it again, this screen pops up again and this time doesn't disappear until anyone leaves the call.

These are my steps:
- Make a call to the mobile client
- Accept the call by tapping the button on the native Call app UI
  > It went into the app
- Go back to the iOS home screen and leave the app

I then tried to tap on the green status bar or the app icon and they both brought me back to the app UI, instead of the native Call UI, which I need to select from the multitask view.
