### ISSUE TITLE
Not getting notification 

### ISSUE THREAD

**Issue by aniketlokhande07** [twilio/voice-quickstart-ios#372]
![Screenshot 2020-07-14 at 4 22 49 PM](https://user-images.githubusercontent.com/29546467/88161759-06a10800-cc2e-11ea-95ba-ec282e7a10e4.png)

I am using apple Apple push notification service SSL(Sandbox and Production), this is universal certificate allow both type of notification, is this certificate works for VoIP push.

**Comment by aniketlokhande07** [comment]
Why am I not receiving any incoming call push notification although the SDK says it registered successfully?
The Twilio Programmable Voice iOS SDK requires Apple’s VoIP Service certificate so that Twilio can send VoIP Push Notifications to your mobile client on your behalf. Twilio will fail to send the push notifications to Apple's VoIP Service endpoint since it is using the regular APNS certificate.

I am using a universal certificate as mention above, that having VoIP services

**Comment by bobiechen-twilio** [comment]
@aniketlokhande07 

Apple's description might be misleading but in order to receive incoming call push notifications for the Voice SDK, please follow the quickstart instructions and use a VoIP Service certificate.

The `TwilioVoice.register()` method only does limited checks such as the length of the device token or the characters/data used in the device token. This is the reason although you are seeing successful registration result but still not receiving incoming push notifications since the Voice iOS SDK requires the Apple VoIP Service certificate.

**Comment by bobiechen-twilio** [comment]
Closing ticket as by-design. @aniketlokhande07 feel free to reach out to the team if you have trouble integrating the VoIP certificate or PushKit in your application.

**Comment by aniketlokhande07** [comment]
Actually you can use one universal certificate for your voip push and normal push. When you send a normal push, use normal topic and normal token, which is generally your bundle identifier

com.company.appname

When you send a VOIP push, use VOIP topic and your pushkit token, which is

com.company.appname.voip

as Twilio sending VoIP push, So is there any configuration like above

**Comment by aniketlokhande07** [comment]
apple provided documentation for this

**Comment by bobiechen-twilio** [comment]
Hi @aniketlokhande07 

Currently Twilio uses the VoIP topic in the VoIP Service certificate for sending notification requests to APNS. We will research about the new APNS certificate and see if and how we can integrate into the system.

Thanks.
