### ISSUE TITLE
Incoming Call Not Received in Xcode Simulator.. Help!

### ISSUE THREAD

**Issue by gildermcd** [twilio/voice-quickstart-ios#377]
Hello, I am new to IOS development, but have followed along with the quick start for Swift several times and am repeatedly encountering issues at step number 10. I have successfully set everything up as far as I can tell, but I am not receiving the incoming call on my simulator in Xcode when I hit the /placeCall.php endpoint. I do not receive any errors or any indication that a call was attempted. The log indicated that there was "no answer". 

One sid that exhibits such behavior is: CA313a9cc5d0a5b13394715532d9fff3d8

Thank you in advance for your help!

**Comment by bobiechen-twilio** [comment]
Hi @gildermcd 

Thanks for reaching out and glad that you were able to get majority of the quickstart working!
Currently push notifications only works on actual devices so you will need to run on an iPhone or iPad in order to receive VoIP pushes for incoming call invites.

Let us know in case you need help with notifications on devices.

Cheers,
-bobie

**Comment by gildermcd** [comment]
Thank you, Bobie. I have got it working now!
