### ISSUE TITLE
[Feature request]API to get duration of a call

### ISSUE THREAD

**Issue by hand228** [twilio/voice-quickstart-ios#381]
Hi there,
Currently, I use a local timer to calculate duration of a voice call. The timer starts in delegate callDidConnect and ends when call disconnected.
I want to ask if there is any API to get this duration from TwilioVoice SDK.

Thanks in advanced

**Comment by bobiechen-twilio** [comment]
Hi @hand228 

The Voice SDK currently does not have any API to provide either the timestamp or the elapsed time of the call. Since for display purpose the application still needs to query call duration from the SDK periodically (most likely every second) and update on the UI, the most the SDK can do is to give a precise timestamp when the call is connected, but eventually the timer still falls back on the application.

**Comment by hand228** [comment]
Thank you @bobiechen-twilio. I got it
So I will continue calculating timestamp locally.
