### ISSUE TITLE
How to Display Caller Id from Phone's Contacts?

### ISSUE THREAD

**Issue by KodyKendall** [twilio/voice-quickstart-ios#441]
I've noticed as calls come in, it doesn't matter if the caller is in my contacts list, they're not resolving to the correct contact and displaying, meaning that caller ID is essentially useless on the phone..

For example, if I call from phone number: "+1 (234) 456-7890"

And that number is saved in my devices contacts as: "Bob"

It displays as: +1234567890

On the CallKit incoming call screen. If I call from that phone directly to my device (not through CallKit), then the contact shows "Bob" as it's ringing in. 

Any thoughts why this might be? How closely must the number match on the contact to make it resolve?

**Comment by bobiechen-twilio** [comment]
Hi @KodyKendall 

I am not the expert of CallKit or the application side design, but I think what is displayed depends on what your application passes in the `CXHandle` object when reporting the incoming call to CallKit. You might also want to add the name/number from the VoIP app to your system contact if that suits your design.

**Comment by fattalgazi** [comment]
I faced same problem, I don't know it's about CallKit itself or Twilio Voice SDK but  this is my hack to solve the problem:

Twilio uses ```twi_from``` parameter in Voip Push data to show the caller name in CallKit.

Step 1) When you initiate the outgoing call on your server side, add a custom parameter like this: 

```
$client->parameter([
	"name" => "x_caller_e164",
	"value" => "".$caller_phone_number
]);
```
Step 2) [On this line](https://github.com/twilio/voice-quickstart-ios/blob/9b6110017a93dd8069d55ba03be04b5dc8297bc0/SwiftVoiceQuickstart/ViewController.swift#L341) before Twilio SDK analyzing Voip data and triggers the ```callInviteReceived``` function, I am manipulating the incoming voip push data. Like:

```
func incomingPushReceived(payload: PKPushPayload, completion: @escaping () -> Void) {
    let modifiedPayload = self.changeUserNameFromContactsBeforeAnalyzing(payload: payload)

    // The Voice SDK will use main queue to invoke `cancelledCallInviteReceived:error:` when delegate queue is not passed
    TwilioVoiceSDK.handleNotification(modifiedPayload, delegate: self, delegateQueue: nil)
    
    if let version = Float(UIDevice.current.systemVersion), version < 13.0 {
        // Save for later when the notification is properly handled.
        incomingPushCompletionCallback = completion
    }
}
private func changeUserNameFromContactsBeforeAnalyzing(payload: PKPushPayload) -> [AnyHashable : Any] {
    let modifiedPayload = payload
    let temp = modifiedPayload.dictionaryPayload as NSDictionary
    let userInfo = temp.mutableCopy() as! NSMutableDictionary

    if let twi_from = userInfo["twi_from"] as? String , x_from.count > 0 {
        //in getContactNameFromContacts function, I am searching twi_from parameter in phone contacts list. code your logic here.
        if let contactName = ContactsPermissionManager.shared.getContactNameFromContacts(twi_from){
            if  contactName.count > 0 {
                userInfo["twi_from"] = contactName
            }
        }
    }

    return userInfo as! [AnyHashable : Any]
}

```

After making those changes, you will see the your contact name in CallKit screen. 

Final note, if you are using callInvite.from object to show caller phone number in your App [like this](https://github.com/twilio/voice-quickstart-ios/blob/9b6110017a93dd8069d55ba03be04b5dc8297bc0/SwiftVoiceQuickstart/ViewController.swift#L378), you will lost the caller ID in this situation, because we have replaced it with the name of the contact, if you need caller phone number as well, that's why I have added ```x_caller_e164``` custom parameter as well. You can fetch the caller phone number like that: 

```
        let realCallerPhoneNumber = callInvite.customParameters?["x_caller_e164"] ?? ""
```

You are done.

One caveat about the hack: Because we change the phone number with the contact's name, if you are using ```INStartAudioCallIntent``` intent, it will not work anymore. (When you tap the call record on phone call history, nothing will be happen, normally, you can redirect user to your app with the phone number tapped.)

**Comment by KodyKendall** [comment]
Thank you!
