### ISSUE TITLE
Unable to create VOIP certificate key for twillio from terminal

### ISSUE THREAD

**Issue by vaibhavtech1302** [twilio/voice-quickstart-ios#446]
Hello,

Can we handle voice call with FCM notification on iOS please send me sample code for FCM if it's possible and I am unable to create key from voip certificate for iOS I would be thankful if I would have video guide to implement this process as I am not getting clear picture of steps.

Thanks!

### Description

I am unable to create key to use web-console from voip certificate. i would be thankful if anyone can send steps for iOS voip pushregistry whole process video. And Can we handle same scenario with FCM Notification if yes please send me code for FCM integration on iOS for twillio call handling.

#### Expected Behavior
I need working steps guide video for voip push registration for sandbox and production both working. If it's possible to handle with FCM can I have code for iOS.

#### Xcode

11.6

#### iOS Version

13.3

#### iOS Device

iPhone XR

**Comment by bobiechen-twilio** [comment]
Hi @vaibhavtech1302 

To provide the best call experience on the latest iOS, Apple encourages VoIP applications to use PushKit and CallKit for their incoming calls. The Voice iOS SDK currently only supports the VoIP Service certificate in order to guarantee the success of push notification delivery. iOS will also allow longer execution time when the notification is received while the app is not active.

Please follow [the steps](https://github.com/twilio/voice-quickstart-ios#6-create-a-push-credential-with-your-voip-service-certificate) in the README to create your Push Credentials using the VoIP Service certificate.

**Comment by vaibhavtech1302** [comment]
Hi @bobiechen-twilio can you please send me video guide for that actually I am following same steps but I am getting RSA is writing instead of creating key from .p12 voip certificate.

**Comment by bobiechen-twilio** [comment]
Hi @vaibhavtech1302 

Thanks for the updates. It looks like the profile of your Twilio CLI has not been set yet. Please use the `twilio profiles` API and corresponding commands to configure the profile for your project.
