### ISSUE TITLE
Error - 52134 Invalid APNs device token 

### ISSUE THREAD

**Issue by sandeepmanala** [twilio/voice-quickstart-ios#498]
### Description
In Twilio dashboard I see error(52134 Invalid APNs device token) and my call not reach out on iphone 12 mini with( iOS 15.3.1) not only with iPhone mini I'm not getting to any device.

#### Expected Behavior

has to receive incoming call

#### Actual Behavior
not getting incoming call

[e.g. 6.3.1 via CocoaPods]

Xcode
[e.g. 13.2.1]

iOS Version
[e.g. 15.3.1]

iOS Device
[e.g. iPhone 12 mini]

**Comment by bobiechen-twilio** [comment]
Hi @sandeepmanala 

Please check if the app environment (dev/production) matches the sandbox option of the Push Credential. Please also provide Twilio Call SIDs if you keep seeing this.

Thanks
-bobie

**Comment by sandeepmanala** [comment]
Hi @bobiechen-twilio 
I'm providing you 
Call SID : CAa7517606fd3c5663d486bf5284056681 (while sandbox unchecked)

Call SID : CA3bc6b52a93c03dde1fd193720a54f0ce (while sandbox checked- no error in twilio logs but not received notification in didReceiveIncomingPushWithPayload)
could you check please

**Comment by bobiechen-twilio** [comment]
Thanks for providing the Call SIDs.

For `CAa7517606fd3c5663d486bf5284056681`, it looks like once the production Push Credential `CR48f62846e4a4fd189cf0d282e9071db8` was created, the push notification deliveries started to succeed and your app should start to receive incoming calls with no problem.

For `CA3bc6b52a93c03dde1fd193720a54f0ce` delivery was successful and I believe this is related to issue 2, which is typically due to the PushKit `PKPushRegistry` instance not being initialized in the frontmost component of the app (preferably AppDelegate) to handle and report the incoming call immediately to CallKit. Please check the example in the quickstart and apply necessary changes to your app.
