### ISSUE TITLE
SwiftUI Example

### ISSUE THREAD

**Issue by softsan** [twilio/voice-quickstart-ios#510]
I see a branch here with swiftUI: https://github.com/twilio/voice-quickstart-ios/tree/swiftui-example/SwiftUIVoiceQuickstart
but seems like there is a little or no progress. Are there any complete example for SwiftUI  with CallKit ?

I am trying to integrate it in SwiftUI and i am getting an error while starting an outgoing call:
Error Domain=com.twilo.voice.error Code=20102 "Invalid Access Token header" UserInfo={NSLocalizedDescription=Invalid Access Token header, NSLocalizedFailureReason=SIP/2.0 403 Forbidden}

I decoded the JWT Token and in header i see this:
{
  "alg": "HS256",
  "typ": "JWT",
  "cty": "JWT"
}

so what could be wrong in above token header?

Thanks

**Comment by bobiechen-twilio** [comment]
Thanks for the interests @softsan 
It's a shame that I haven't got time to continue working on that branch, but since it's the same SDK APIs so developer should be able to put together their app with SwiftUI.

Since the code is incomplete, we don't expect it to run the full SDK functionalities, but if you check out this you will find that the token is empty and should be filled in by the app developer when running the quickstart: https://github.com/twilio/voice-quickstart-ios/blob/swiftui-example/SwiftUIVoiceQuickstart/ContentView.swift#L10
